sudo: required
services:
- docker
language: cpp

env:
  matrix:
  - JOB_ARCH=amd64
  - JOB_ARCH=arm64
  - JOB_ARCH=armel
  - JOB_ARCH=armhf
  - JOB_ARCH=i386
  - JOB_ARCH=mips
  - JOB_ARCH=mips64el
  - JOB_ARCH=mipsel
  - JOB_ARCH=ppc64el
  - JOB_ARCH=s390x
  global:
  - DOCKER_EXEC_ROOT="docker exec --user root test_container"
  - DOCKER_EXEC="docker exec test_container"
  - BINTRAY_USER=laarid
  - BINTRAY_REPO=main
  - BINTRAY_COMPONENT=main
  - BINTRAY_DESC="Android libunwind"

matrix:
  fast_finish: true
  allow_failures:
  - env: JOB_ARCH=s390x

addons:
  apt:
    packages:
    - dpkg-dev

before_install:
- docker run --rm --privileged vicamo/binfmt-qemu:latest
- cat /proc/sys/fs/binfmt_misc/qemu-*
- |
  export JOB_SUITE=$(dpkg-parsechangelog | grep ^Distribution: | awk '{print $2}')
- |
  docker run --detach --tty \
    --name test_container \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --workdir ${TRAVIS_BUILD_DIR} \
    --add-host dl.bintray.com:$(nslookup dl.bintray.com | grep -m1 -A1 Name: | grep Address: | awk '{print $2}') \
    laarid/devel:${JOB_SUITE}-${JOB_ARCH} \
    /bin/bash

install:
- ${DOCKER_EXEC_ROOT} chown --recursive laarid:laarid ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}
- ${DOCKER_EXEC_ROOT} apt-get update -qq
- ${DOCKER_EXEC} mk-build-deps
    --host-arch ${JOB_ARCH}
    --install --remove
    --root-cmd sudo
    --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y --allow-unauthenticated'

script:
- ${DOCKER_EXEC} env
      "DEB_BUILD_OPTIONS=nocheck"
    dpkg-buildpackage
      --host-arch ${JOB_ARCH}
      -i -us -uc -b
- ${DOCKER_EXEC} make -C build -j $(nproc) distcheck
- git status; git status | grep 'working tree clean'

before_deploy:
- sudo chown --recursive $(id --user):$(id --group) ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}
- |
  cat .bintray.json.in | \
    sed -e "s#@BINTRAY_PACKAGE@#$(dpkg-parsechangelog | grep ^Source: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
        -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
        -e "s#@BINTRAY_DESC@#${BINTRAY_DESC}#g" \
        -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
        -e "s#@BINTRAY_VERSION@#$(dpkg-parsechangelog | grep ^Version: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_RELEASE_DATE@#$(date -Iseconds --date="$(dpkg-parsechangelog | grep ^Date: | cut -d ' ' -f 2-)")#g" \
        -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
        -e "s#@BINTRAY_POOLABBR@#$(dpkg-parsechangelog | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
        -e "s#@BINTRAY_SUITE@#${JOB_SUITE}#g" \
        -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
        -e "s#@BINTRAY_ARCH@#${JOB_ARCH}#g" | \
    tee bintray.json

deploy:
- provider: bintray
  file: bintray.json
  user: vicamo
  key:
    secure: "wVx5abXG8LOs58kuyH+ARx6HpIBoi/iviNTB38T2K1XlNUxs1R5Qoll33Iubu+TfltTbJQBkQXBwsGs5bxmUlngzObQgHxi5dandsgu+GGhdTiWkKhx4OvWFEVvYpsiPiMbUiYGUkJ1S0PE2qRYmRaj4wNyb2Er5q8hdpbCFLSViDhhSAIqYJGKri+cmcSco0/4KhDuFrYGyh2cXQ4kuSDneO/e4KpfU9DGIgFxCn1fHStKb858zcFuYYpqMlN/c4+n+aNuI6qsn6BM2md1Nl4vo5DLW6Q2lvwhlchbJ8EOBNBVwUBdkPF8g0W8frXjTnNaknKtfioFXrVH/A+QN+lIQp2xK/OS2D4SmceLIMfSPm8E7mHQkDM1QfP9y0Bo2VcSmcE9azQZi6Z0cMvGzznSNT2KAWqoyR9unXQHPNGo6uJzZdS4j6KUy6bK54hTTHRL2B9nA0GrASqADQxLVlwEBp/cRJ4WMezZA4yTxc7OYDWI/2Uv+SJgOL/eP5eMzczHmf8uj+uYd8iGPmSSh3/4tNFvKz6/3CZMwqVbLXQVEiMz60PRL5NfLiRhisssvwuqjGKNTXlJtZuTEm9WHHYuvXlY3muzerxTz7+8WuNUFnK94nUtmtNgP9KSSwKpQUBbH+P8NqioROdyfBkv9IIpaKtCZGABpn1/Fmi6MfBU="
  on:
    tags: true

notifications:
  slack:
    rooms:
    - secure: "PB2lEYzGZ+032BtJom+0Bu8d3Y2g1hVXfoqBaHg32UFFHVahCjZtOzmW0hFobX2pNLpNldVoBBgsBgJwCdetXxRv550ow7kqZwt1Y0DQZ9i1jOYlQnAhq3TtbtOSXfrIDGD0LG8UxSd/nQZwLd7uPYOu3GfN+NmCOWF80hzWGQpKmRIA16YSg2qjiVJwrSixkN0HrRSA0lgGEwdXGtSMHpOlOvB3xqvgVJTCOyrrw7BGK71StSKtI75kT7WxgOKhbZRdCc2dju0uufXYh9Wjxyp6AVoVP/+1Cl5bsvZ0A28mlVFXRbpqcY8A155KmvVRWlyYKRtOpyxrT70XiP7/WB1Gx0jAI7E4Aco4o70PTrqQL0agtj3QOdFtuX/p5cRN5ixBAUH176OITMnFxlyxcTqbHq4Glo9c0DVZHKOrZ1/MZtEhZEttv9+Pvew9rcf70DgQo86RomihwEQZdkvDhraNX68vbL/TvjzGUr0G+eRpxKtXre/IwJVLLbsr0k4W0jaq4PXGRIGpjJSeEtHvl4HDexMTl/bWtPN37vojvo/SgeQBkIlx8b/f2vw4nlVZmEJzazNmZ72iusNNnY7e9Rfon4x3PQGrXl1VI3yUkrVu7Fl7HfFjmYtIIqv2XRZqF9aYbgmdrIEW5cWv039XdPfyh8pE35Q81k47bIIblvs="
